---
- name: Deploy Application
  hosts: k8s_master
  become: false
  tasks:
    - name: Create deployment manifest
      copy:
        dest: ~/app-deployment.yml
        content: |
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: sample-app
          spec:
            replicas: 2
            selector:
              matchLabels:
                app: sample-app
            template:
              metadata:
                labels:
                  app: sample-app
              spec:
                containers:
                - name: nginx
                  image: nginx:latest
                  ports:
                  - containerPort: 80
          ---
          apiVersion: v1
          kind: Service
          metadata:
            name: sample-app-service
          spec:
            type: NodePort
            selector:
              app: sample-app
            ports:
            - port: 80
              targetPort: 80
              nodePort: 30080

    - name: Deploy application
      command: kubectl apply -f ~/app-deployment.yml
